# Generated by Django 3.1.3 on 2020-11-11 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewscounter',
            name='uniqueViews',
        ),
    ]
